### PR TITLE
Team5submit

### PR DESCRIPTION
**Pull request by mgpauly1458**

### CODE REVIEW

**Comment by bmurmann** [comment]
Your _sim netlist has the wrong format.

**Comment by bmurmann** [comment]
Your _sim netlist has the wrong format.

**Comment by mgpauly1458** [comment]
Did that fix things? I also changed the symbol to 'primitive'.

**Comment by bmurmann** [comment]
Almost. There should be no .inc code snippets in your netlist. These things belong only in testbenches.

Also, if you could remove the ** at the top in  **.subckt Team5 vhi vlo vdda vssa vin dd res clkin and the corresponding .ends, it would be appreciated (as mentioned on Discord).

**Comment by mgpauly1458** [comment]
I found a hidden .inc code statement in the clockgen, that must've been the problem. I also removed the ** at the .bubckt, and at the .ends on line 15.

**Pull request merged**
